[build]
publish = "_site/"
command = "yarn run build"

[context.branch-deploy]
command = "export BASE_URL=$DEPLOY_PRIME_URL && yarn run build"

[context.deploy-preview]
command = "export BASE_URL=$DEPLOY_PRIME_URL && yarn run build"

[dev]
command = "yarn start"

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "ALLOW"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Content-Security-Policy = "frame-origin 'none';"

[[redirects]]
from = "/api/*"
to = "https://api.collegemusic.co.uk/api/:splat"
status = 200
force = true
headers = { X-From = "Netlify" }
